import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from "../lib/query"
import Product from '../components/Products'
import { Gallery } from '../styles/Gallery'
import SearchBar from '../components/searchBar'
import useState from "react"
export default function Home() {
  const [results] = useQuery({query: PRODUCT_QUERY})
  const {data, fetching, error} = results
  if (fetching) return <p>Loading your content...</p>
  if (error) return <p>An error has occured: {error.message}</p>
  const products = data.products.data
  return (
    <div>
      <Head>
        <title>Pyramid Scheme Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>
      <h1>Hello Future Millionaires!</h1>
      <SearchBar data = {products}/> 
      </main>
    </div>

     
  );
}
