import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from "../lib/query"
import Cover from'../components/Cover'
import Review from '../components/Review'

export default function Home() {
  const [results] = useQuery({query: PRODUCT_QUERY})
  const {data, fetching, error} = results
  if (fetching) return <p>Loading your content...</p>
  if (error) return <p>An error has occured: {error.message}</p>
  const products = data.products.data
  return (
    <div>
      <Head>
        <title>Pyramid Scheme Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"/>
      </Head>

      <main>
        <Cover></Cover>
<div class="text-divider" id = "second-section">TESTIMONIALS</div>
<Review/>
<Review/>
<footer>

</footer>
      </main>
    </div>

     
  );
}
